---
 - hosts: Client
   tasks:
   - name: Update debian
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   - name: Sending website address
     copy:
        src: address
        dest: /address

